apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-operator
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: cluster-config
  source:
    path: components/apps/operators/eso/aggregate/
    repoURL: https://github.com/turbra/cluster-config.git
    targetRevision: lab
  syncPolicy:
    automated:
      selfHeal: true
      prune: true