apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../components/argocd/compliance
- ../../components/argocd/container-security
- ../../components/argocd/acs
- ../../components/argocd/sealed-secrets
- ../../components/argocd/oauth

