apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: sso-db-sso-user
      key: username
    passwordSecret:
      name: sso-db-sso-user
      key: password
  hostname:
    hostname: keycloak.apps.prox.turbra
  proxy:
    headers: forwarded
  resources:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      memory: 850Mi
      cpu: 100m