namespace: test-db

bases:
  - ../../base/

patches:
  - target:
      group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: test-db
    path: postgres-cluster.yaml