apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: banner
spec:
  text: "Proxmox Lab"
  location: BannerTop
  color: '#fff'
  backgroundColor: 'F28C28'
  link:
    href: https://github.com/turbra/cluster-config
    text: "cluster-config"
