apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogForwarder"
metadata:
  name: "instance" 
  namespace: "openshift-logging" 
spec:
  outputs:
    - name: splunk-receiver 
      secret:
        name: vector-splunk-secret 
      type: splunk 
      url: http://splunk-standalone-sample-standalone-service.splunk-operator.svc:8088
  pipelines: 
    - inputRefs:
        - application
        - infrastructure
      name: forward-to-splunk
      outputRefs:
        - splunk-receiver
