apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogForwarder"
metadata:
  name: "instance" 
  namespace: "openshift-logging" 
spec:
  outputs:
    - name: splunk-receiver 
      secret:
        name: vector-splunk-secret 
      type: splunk 
      url: http://splunk-standalone-sample-standalone-service.splunk-operator.svc.cluster.local:8088
    - name: default 
      type: elasticsearch 
      url: https://elasticsearch.openshift-logging.svc:9200 
  pipelines: 
    - inputRefs:
        - application
        - infrastructure
      name: forward-to-splunk
      outputRefs:
        - splunk-receiver
    - inputRefs:
        - application
        - infrastructure
      name: forward-to-internal-es
      outputRefs:
        - default

