apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  serviceAccount:
    name: logcollector
  outputs:
  - name: splunk-hec
    type: splunk
    splunk:
      url: http://192.168.1.2:8088
      authentication:
        token:
          secretName: vector-splunk-secret
          key: hecToken
  pipelines:
  - name: all-to-splunk
    inputRefs:     [application, infrastructure, audit]
    outputRefs:    [splunk-hec]

