apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: defrag-etcd
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: cluster-config
  source:
    path: components/apps/cluster-config/defrag-etcd
    repoURL: https://github.com/turbra/cluster-config.git
    targetRevision: lab
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
