apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs
spec:
  applicationMenu:
    imageURL: >-
      https://console-openshift-console.apps.july.hyperv.lab/static/assets/redhat.svg
    section: OpenShift ACS
  href: 'https://console-openshift-console.apps.july.hyperv.lab/'
  location: ApplicationMenu
  text: Advanced Cluster Security
