apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs
spec:
  applicationMenu:
    imageURL: >-
      https://central-stackrox.apps.july.hyperv.lab/static/media/RHACS-Logo.d3245b7c3ef3347be06f35cae343c70a.svg
    section: OpenShift ACS
  href: 'https://central-stackrox.apps.july.hyperv.lab/'
  location: ApplicationMenu
  text: Advanced Cluster Security
