apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: gitlab
spec:
  applicationMenu:
    imageURL: >-
      https://gitlab.com/uploads/-/system/user/avatar/14076091/avatar.png
    section: GitLab
  href: 'https://gitlab.com/turbra'
  location: ApplicationMenu
  text: GitLab
