kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
- ../../base

patches:
  - target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster
    path: htpasswd-patch.json
