apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: banner
spec:
  text: "${ENV_NAME} Cluster: ${CLUSTER_NAME}"
  location: BannerTop
  color: '#fff'
  backgroundColor: 'F28C28'
  link:
    href: https://console.redhat.com/openshift/details/${CLUSTER_ID}
    text: "(${CLUSTER_ID})"
