kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- htpasswd-sealedsecret.yaml
- oauth.yaml
- turbra-crb.yaml
- cluster-admins-group.yaml
- cluster-admins-crb.yaml

#patches:
#  - target:
#      group: config.openshift.io
#      version: v1
#      kind: OAuth
#      name: cluster
#    path: sso-patch.json
