apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs
spec:
  applicationMenu:
    imageURL: >-
      https://console-openshift-console.apps.hub.turbra/static/assets/redhat.svg
    section: OpenShift ACS
  href: 'https://central-stackrox.apps.hub.turbra.lab/'
  location: ApplicationMenu
  text: Advanced Cluster Security
