apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: cluster-config-monitoring
    namespace: openshift-gitops
  patch: |-
    - op: replace
      path: /spec/source/path
      value: components/apps/cluster-config/monitoring/overlays/aws
