apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: central
  namespace: stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  monitoring:
    openshift:
      enabled: true
  central:
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    telemetry:
      enabled: true
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: central-db
      resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 512Mi
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      scaling:
        autoScaling: Disabled
        #maxReplicas: 5
        #minReplicas: 2
        replicas: 2
