apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  namespace: stackrox
spec:
  template:
    spec:
      containers:
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
          requests:
            cpu: '1'
            memory: 2Gi
