apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    chart: sealed-secrets
    helm:
      parameters:
      - name: namespace
        value: sealed-secrets
    path: components/apps/operators/sealed-secrets-operator/overlays/default
    repoURL: https://github.com/turbra/cluster-config.git
    targetRevision: lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
